### ISSUE TITLE
Capacitor v6

### ISSUE THREAD

**Issue by NielsPrins** [jkbz64/capacitor-datawedge#14]
Thank you for the plugin!
Can you update it to support Capacitor v6

**Comment by NielsPrins** [comment]
[https://capacitorjs.com/docs/updating/plugins/6-0](https://capacitorjs.com/docs/updating/plugins/6-0)

There is an migration command:
`npx @capacitor/plugin-migration-v5-to-v6@latest`

**Comment by jkbz64** [comment]
Deployed in `capacitor-datawedge@0.3.3`, please try it out and tell me if it works for you.

**Comment by NielsPrins** [comment]
Yes it works! Thank you
