### ISSUE TITLE
Error when using with Android 14

### ISSUE THREAD

**Issue by Saboti215** [jkbz64/capacitor-datawedge#15]
I've got some troubles using this plugin with Android 14.
After some research, I noticed that the flags `RECEIVER_EXPORTED `/ `RECEIVER_NOT_EXPORTED` seems to be required in android 14.

I also prepared a solution for this in my fork: https://github.com/Saboti215/capacitor-datawedge/tree/register-receiver-fix-android-13

My solution is also working on android versions <13 and I've tested this successfully in android 14.

**Comment by jkbz64** [comment]
Does #16 close this? (I think so?)

**Comment by Saboti215** [comment]
Yes, thanks for merging this pr!
