### ISSUE TITLE
Capacitor v4

### ISSUE THREAD

**Issue by AndreaMinato** [jkbz64/capacitor-datawedge#4]
Thank you for this plugin,
Is it planned to add support to capacitor v4?

**Comment by jkbz64** [comment]
I'll look into it when I will have some free time, probably does not need a lot of modifications, the v4 did not seem to change much for plugins (I think).
If you know what needs to be changed and want to do it feel free to send a pr, the plugin codebase is not far off from plugin template.

**Comment by jkbz64** [comment]
Should be fixed after #5 and 0c4bf8d985cb9cc1d47a072b608c253c8e7e61ef
